"""add interested_project_id to leads

Revision ID: 1345def27bd5
Revises: d176359d00dd
Create Date: 2026-07-01 13:47:47.031697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1345def27bd5'
down_revision: Union[str, None] = 'd176359d00dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('interested_project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leads_interested_project_id'), 'leads', ['interested_project_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'projects', ['interested_project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_interested_project_id'), table_name='leads')
    op.drop_column('leads', 'interested_project_id')
    # ### end Alembic commands ###
