"""add notaries tax_records notary_fees

Revision ID: 1a9270faba2e
Revises: ce5748dc1cdd
Create Date: 2026-07-01 15:50:43.920744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9270faba2e'
down_revision: Union[str, None] = 'ce5748dc1cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notaries',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('office', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notaries_tenant_id'), 'notaries', ['tenant_id'], unique=False)
    op.create_table('notary_fees',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('notary_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notary_id'], ['notaries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notary_fees_client_id'), 'notary_fees', ['client_id'], unique=False)
    op.create_index(op.f('ix_notary_fees_notary_id'), 'notary_fees', ['notary_id'], unique=False)
    op.create_index(op.f('ix_notary_fees_tenant_id'), 'notary_fees', ['tenant_id'], unique=False)
    op.create_table('tax_records',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('notary_id', sa.UUID(), nullable=True),
    sa.Column('tax_type', sa.Enum('PPH', 'BPHTB', 'PPN', name='taxtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id_billing', sa.String(length=50), nullable=True),
    sa.Column('ntpn', sa.String(length=50), nullable=True),
    sa.Column('tax_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('BELUM', 'DIBAYAR', 'VALIDASI', 'DTP', 'BEBAS', name='taxstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notary_id'], ['notaries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_records_client_id'), 'tax_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_tax_records_notary_id'), 'tax_records', ['notary_id'], unique=False)
    op.create_index(op.f('ix_tax_records_tenant_id'), 'tax_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_records_tenant_id'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_notary_id'), table_name='tax_records')
    op.drop_index(op.f('ix_tax_records_client_id'), table_name='tax_records')
    op.drop_table('tax_records')
    op.drop_index(op.f('ix_notary_fees_tenant_id'), table_name='notary_fees')
    op.drop_index(op.f('ix_notary_fees_notary_id'), table_name='notary_fees')
    op.drop_index(op.f('ix_notary_fees_client_id'), table_name='notary_fees')
    op.drop_table('notary_fees')
    op.drop_index(op.f('ix_notaries_tenant_id'), table_name='notaries')
    op.drop_table('notaries')
    # ### end Alembic commands ###
