"""payments attach to client (alur b)

Revision ID: 5735e92a9cf5
Revises: e0b3cc430f04
Create Date: 2026-07-01 15:22:54.828232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5735e92a9cf5'
down_revision: Union[str, None] = 'e0b3cc430f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_schedules', sa.Column('client_id', sa.UUID(), nullable=True))
    op.alter_column('payment_schedules', 'sale_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payment_schedules_client_id'), 'payment_schedules', ['client_id'], unique=False)
    op.create_foreign_key(None, 'payment_schedules', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('client_id', sa.UUID(), nullable=True))
    op.alter_column('payments', 'sale_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payments_client_id'), 'payments', ['client_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_client_id'), table_name='payments')
    op.alter_column('payments', 'sale_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('payments', 'client_id')
    op.drop_constraint(None, 'payment_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_payment_schedules_client_id'), table_name='payment_schedules')
    op.alter_column('payment_schedules', 'sale_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('payment_schedules', 'client_id')
    # ### end Alembic commands ###
