"""procurement: soft-delete, alloc, vendor payments

Revision ID: 9c21984165ee
Revises: dbe9a9a6d064
Create Date: 2026-07-02 08:00:59.206259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c21984165ee'
down_revision: Union[str, None] = 'dbe9a9a6d064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_payments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('method', sa.Enum('TRANSFER', 'TUNAI', 'LAINNYA', name='vendorpaymentmethod'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_payments_purchase_order_id'), 'vendor_payments', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_vendor_payments_tenant_id'), 'vendor_payments', ['tenant_id'], unique=False)
    op.alter_column('purchase_order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_purchase_order_items_purchase_order_id'), 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.add_column('purchase_orders', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('purchase_orders', sa.Column('unit_id', sa.UUID(), nullable=True))
    op.add_column('purchase_orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('purchase_orders', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('purchase_orders', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('purchase_orders', 'po_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_purchase_orders_project_id'), 'purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_unit_id'), 'purchase_orders', ['unit_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.drop_constraint('purchase_orders_vendor_id_fkey', 'purchase_orders', type_='foreignkey')
    op.drop_constraint('purchase_orders_approved_by_fkey', 'purchase_orders', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_orders', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'purchase_orders', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'purchase_orders', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('purchase_orders', 'approved_by')
    op.add_column('vendors', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('vendors', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'deleted_at')
    op.drop_column('vendors', 'is_deleted')
    op.add_column('purchase_orders', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.create_foreign_key('purchase_orders_approved_by_fkey', 'purchase_orders', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('purchase_orders_vendor_id_fkey', 'purchase_orders', 'vendors', ['vendor_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_unit_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_id'), table_name='purchase_orders')
    op.alter_column('purchase_orders', 'po_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('purchase_orders', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('purchase_orders', 'deleted_at')
    op.drop_column('purchase_orders', 'is_deleted')
    op.drop_column('purchase_orders', 'unit_id')
    op.drop_column('purchase_orders', 'project_id')
    op.drop_index(op.f('ix_purchase_order_items_purchase_order_id'), table_name='purchase_order_items')
    op.alter_column('purchase_order_items', 'quantity',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_vendor_payments_tenant_id'), table_name='vendor_payments')
    op.drop_index(op.f('ix_vendor_payments_purchase_order_id'), table_name='vendor_payments')
    op.drop_table('vendor_payments')
    # ### end Alembic commands ###
