"""soft-delete clients payments schedules

Revision ID: ce5748dc1cdd
Revises: 5735e92a9cf5
Create Date: 2026-07-01 15:37:29.250075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5748dc1cdd'
down_revision: Union[str, None] = '5735e92a9cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment_schedules', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('payment_schedules', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('payments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'deleted_at')
    op.drop_column('payments', 'is_deleted')
    op.drop_column('payment_schedules', 'deleted_at')
    op.drop_column('payment_schedules', 'is_deleted')
    op.drop_column('clients', 'deleted_at')
    op.drop_column('clients', 'is_deleted')
    # ### end Alembic commands ###
