"""add sales table

Revision ID: d176359d00dd
Revises: 30c9a7370474
Create Date: 2026-07-01 13:08:22.430789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd176359d00dd'
down_revision: Union[str, None] = '30c9a7370474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('sale_number', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('SUBSIDI', 'KOMERSIAL', name='salecategory'), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH_KERAS', 'CASH_BERTAHAP', 'KPR', name='paymenttype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('akad_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('BOOKING', 'PROSES', 'AKAD', 'LUNAS', 'BATAL', name='salestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_client_id'), 'sales', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sales_unit_id'), 'sales', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_unit_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_client_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
