"""add banks and kpr_applications

Revision ID: dbe9a9a6d064
Revises: 56d2ae96562a
Create Date: 2026-07-01 16:07:12.870738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe9a9a6d064'
down_revision: Union[str, None] = '56d2ae96562a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banks_tenant_id'), 'banks', ['tenant_id'], unique=False)
    op.create_table('kpr_applications',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('COLLECT_BERKAS', 'BERKAS_MASUK_BANK', 'SP3K', 'AKAD_KREDIT', 'PENCAIRAN', name='kprstage'), nullable=False),
    sa.Column('plafond', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tenor_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sp3k_number', sa.String(length=100), nullable=True),
    sa.Column('sikasep_number', sa.String(length=100), nullable=True),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('sp3k_date', sa.Date(), nullable=True),
    sa.Column('akad_date', sa.Date(), nullable=True),
    sa.Column('pencairan_date', sa.Date(), nullable=True),
    sa.Column('pencairan_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pencairan_payment_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pencairan_payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpr_applications_bank_id'), 'kpr_applications', ['bank_id'], unique=False)
    op.create_index(op.f('ix_kpr_applications_client_id'), 'kpr_applications', ['client_id'], unique=False)
    op.create_index(op.f('ix_kpr_applications_tenant_id'), 'kpr_applications', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpr_applications_tenant_id'), table_name='kpr_applications')
    op.drop_index(op.f('ix_kpr_applications_client_id'), table_name='kpr_applications')
    op.drop_index(op.f('ix_kpr_applications_bank_id'), table_name='kpr_applications')
    op.drop_table('kpr_applications')
    op.drop_index(op.f('ix_banks_tenant_id'), table_name='banks')
    op.drop_table('banks')
    # ### end Alembic commands ###
