"""extend clients: address project unit marketing promo signature

Revision ID: e0b3cc430f04
Revises: 9d2127947397
Create Date: 2026-07-01 14:24:12.628946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b3cc430f04'
down_revision: Union[str, None] = '9d2127947397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('clients', sa.Column('unit_id', sa.UUID(), nullable=True))
    op.add_column('clients', sa.Column('marketing_user_id', sa.UUID(), nullable=True))
    op.add_column('clients', sa.Column('promo', sa.String(length=200), nullable=True))
    op.add_column('clients', sa.Column('signature', sa.Text(), nullable=True))
    op.create_index(op.f('ix_clients_marketing_user_id'), 'clients', ['marketing_user_id'], unique=False)
    op.create_index(op.f('ix_clients_project_id'), 'clients', ['project_id'], unique=False)
    op.create_index(op.f('ix_clients_unit_id'), 'clients', ['unit_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'clients', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'clients', 'users', ['marketing_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_unit_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_project_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_marketing_user_id'), table_name='clients')
    op.drop_column('clients', 'signature')
    op.drop_column('clients', 'promo')
    op.drop_column('clients', 'marketing_user_id')
    op.drop_column('clients', 'unit_id')
    op.drop_column('clients', 'project_id')
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###
