"""add contractor_contracts + expense.contract_id

Revision ID: e30e2d22800a
Revises: f2f2f099d310
Create Date: 2026-07-02 10:36:58.751502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30e2d22800a'
down_revision: Union[str, None] = 'f2f2f099d310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_contracts',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_contracts_project_id'), 'contractor_contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_tenant_id'), 'contractor_contracts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_unit_id'), 'contractor_contracts', ['unit_id'], unique=False)
    op.create_index(op.f('ix_contractor_contracts_vendor_id'), 'contractor_contracts', ['vendor_id'], unique=False)
    op.add_column('expenses', sa.Column('contract_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expenses_contract_id'), 'expenses', ['contract_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'contractor_contracts', ['contract_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_contract_id'), table_name='expenses')
    op.drop_column('expenses', 'contract_id')
    op.drop_index(op.f('ix_contractor_contracts_vendor_id'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_contractor_contracts_unit_id'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_contractor_contracts_tenant_id'), table_name='contractor_contracts')
    op.drop_index(op.f('ix_contractor_contracts_project_id'), table_name='contractor_contracts')
    op.drop_table('contractor_contracts')
    # ### end Alembic commands ###
