"""add unit_constructions

Revision ID: f2f2f099d310
Revises: fd5e7086978d
Create Date: 2026-07-02 10:24:13.535564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2f2f099d310'
down_revision: Union[str, None] = 'fd5e7086978d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_constructions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('PERSIAPAN', 'PONDASI', 'STRUKTUR', 'DINDING', 'ATAP', 'FINISHING', 'SELESAI', name='constructionstage'), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_constructions_project_id'), 'unit_constructions', ['project_id'], unique=False)
    op.create_index(op.f('ix_unit_constructions_tenant_id'), 'unit_constructions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_unit_constructions_unit_id'), 'unit_constructions', ['unit_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_constructions_unit_id'), table_name='unit_constructions')
    op.drop_index(op.f('ix_unit_constructions_tenant_id'), table_name='unit_constructions')
    op.drop_index(op.f('ix_unit_constructions_project_id'), table_name='unit_constructions')
    op.drop_table('unit_constructions')
    # ### end Alembic commands ###
