"""add rab templates, adjustments, unit.rab_template_id

Revision ID: fd5e7086978d
Revises: 16054e639576
Create Date: 2026-07-02 10:09:54.369050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fd5e7086978d'
down_revision: Union[str, None] = '16054e639576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rab_templates',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rab_templates_project_id'), 'rab_templates', ['project_id'], unique=False)
    op.create_index(op.f('ix_rab_templates_tenant_id'), 'rab_templates', ['tenant_id'], unique=False)
    op.create_table('rab_template_lines',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('MATERIAL', 'UPAH', 'KONTRAKTOR', 'OPERASIONAL', 'PERIZINAN', 'LAIN', name='expensecategory', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['rab_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rab_template_lines_template_id'), 'rab_template_lines', ['template_id'], unique=False)
    op.create_index(op.f('ix_rab_template_lines_tenant_id'), 'rab_template_lines', ['tenant_id'], unique=False)
    op.create_table('unit_rab_adjustments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM('MATERIAL', 'UPAH', 'KONTRAKTOR', 'OPERASIONAL', 'PERIZINAN', 'LAIN', name='expensecategory', create_type=False), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_rab_adjustments_tenant_id'), 'unit_rab_adjustments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_unit_rab_adjustments_unit_id'), 'unit_rab_adjustments', ['unit_id'], unique=False)
    op.add_column('units', sa.Column('rab_template_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_units_rab_template_id'), 'units', ['rab_template_id'], unique=False)
    op.create_foreign_key(None, 'units', 'rab_templates', ['rab_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_index(op.f('ix_units_rab_template_id'), table_name='units')
    op.drop_column('units', 'rab_template_id')
    op.drop_index(op.f('ix_unit_rab_adjustments_unit_id'), table_name='unit_rab_adjustments')
    op.drop_index(op.f('ix_unit_rab_adjustments_tenant_id'), table_name='unit_rab_adjustments')
    op.drop_table('unit_rab_adjustments')
    op.drop_index(op.f('ix_rab_template_lines_tenant_id'), table_name='rab_template_lines')
    op.drop_index(op.f('ix_rab_template_lines_template_id'), table_name='rab_template_lines')
    op.drop_table('rab_template_lines')
    op.drop_index(op.f('ix_rab_templates_tenant_id'), table_name='rab_templates')
    op.drop_index(op.f('ix_rab_templates_project_id'), table_name='rab_templates')
    op.drop_table('rab_templates')
    # ### end Alembic commands ###
